env:
  es2021: true
  node: true

extends:
  - airbnb-base
  - prettier

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-unused-vars: warn # warning less invasive while developing
  no-plusplus: # common shortcut in for loops
    - error
    - allowForLoopAfterthoughts: true
  no-console: warn
  ########## Below are interesting rules from
  ########## https://github.com/iamturns/create-exposed-app/blob/master/.eslintrc.js
  # Allow function hoisting to improve code readability
  no-use-before-define:
    - error
    - functions: false
      classes: true
      variables: true
  # https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html
  import/prefer-default-export: off
  import/no-default-export: error
  # https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904
  react/jsx-filename-extension: off
